# Generated by Django 3.1.5 on 2021-04-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_t'),
    ]

    operations = [
        migrations.DeleteModel(
            name='T',
        ),
    ]
